default : &default
  adapter: mysql2
  encoding: utf8mb4
  collation : utf8mb4_unicode_ci
  username:
  password: !
  host: localhost

development:
  <<: *default
  database: sleepinglion_development

test:
  <<: *default
  database: sleepinglion_test

